
- name: 'be sure homebrew cask packages is installed'
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - virtualbox
    - vagrant
    - java
    - docker
    - visual-studio-code
    - charles
    - iterm2

